---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: Add an Apt signing key, uses whichever key is at the URL
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: copiar archivo /etc/apt/sources.list.d/kubernetes.list
    copy:
      src: files/kubernetes.list
      dest: /etc/apt/sources.list.d/kubernetes.list

  - name: Instalando paquetes
    package: name={{ item }} state=latest
    loop:
      - emacs-nox
      - tcpdump
      - telnet
      - sysstat
      - wget
      - iotop
      - curl
      - docker
      - docker-compose
      - net-tools
      - kubectl
      - libvirt-clients
      - cpu-checker
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virtinst
      - virt-manager
      - openssh-server
      - yaml-mode
      - python3-pygments
      - tmux
      - minidlna
      - python3-venv

  - name: copiar archivo stern
    copy:
      src: files/stern
      dest: /home/roldyx/bin/stern

