---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  #become_user: 
    
  tasks:
  - name: Add an Apt signing key, uses whichever key is at the URL
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
      
  - name: Basic usage
    debug:
      msg: "{{ lookup('env', 'HOME') }}/bin"
    
  - name: copiar archivo /etc/apt/sources.list.d/kubernetes.list
    copy:
      src: files/kubernetes.list
      dest: /etc/apt/sources.list.d/kubernetes.list

  - name: Instalando paquetes
    package: name={{ item }} state=latest
    loop:
      - emacs-nox
      - tcpdump
      - telnet
      - sysstat
      - wget
      - iotop
      - curl
      - net-tools
      - libvirt-clients
      - cpu-checker
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virtinst
      - virt-manager
      - openssh-server
      - yaml-mode
      - python3-pygments
      - tmux
      - minidlna
      - python3-venv
      - fish
      - fonts-powerline

  - name: Creates directory
    file:
      path: "{{ lookup('env', 'HOME') }}/bin"
      state: directory

  - name: install kubecolor
    get_url:
      url: https://github.com/hidetatz/kubecolor/releases/download/v0.0.20/kubecolor_0.0.20_Linux_x86_64.tar.gz
      dest: "/tmp"
      mode: '0740'

