---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: Add an Apt signing key, uses whichever key is at the URL
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: copiar archivo /etc/apt/sources.list.d/kubernetes.list
    copy:
      src: files/kubernetes.list
      dest: /etc/apt/sources.list.d/kubernetes.list

  - name: Instalando paquetes
    package: name={{ item }} state=latest
    loop:
      - emacs-nox
      - tcpdump
      - telnet
      - sysstat
      - wget
      - iotop
      - curl
      - docker
      - docker-compose
      - net-tools
      - qbittorrent
      - python3-pip
      - kubectl
      - libvirt-clients
      - vlc
      - cpu-checker
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virtinst
      - virt-manager
      - openssh-server
      - yaml-mode
      - python3-pygments
      - tmux
      - minidlna
      - python3-venv

  - name: Find and replace
    lineinfile:
      dest: /home/roldyx/.config/qBittorrent/qBittorrent.conf
      regexp: "Downloads.SavePath"
      line: Downloads\SavePath=/home/roldyx/pelis
      state: present

      
  - name: copiar archivo home roldyx .tmux.conf
    copy:
      src: files/tmux.conf
      dest: /home/roldyx/.tmux.conf

  # QUEDO DEPRECADO EN UBUNTU 2020.04
  # - name: instalar amule
  #   package:
  #     name: amule


  - name: insertar linea 
    lineinfile:
      path: /etc/minidlna.conf
      line: media_dir=V,/home/roldyx/pelis
      insertafter: media_dir=/var/lib/minidlna

  - name: Creamos el grupo 'cuzca' si no existe
    group:
      name: cuzca
      state: present

  - name: Añadimos el grupo 'cuzca' a sudoers sin necesidad de contraseña
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%cuzca'
      line: '%cuzca ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
      
  - name: Añadir usuario 'cuzca' al grupo 'cuzca'
    action: user name=cuzca groups=cuzca append=yes state=present shell=/bin/bash
    
  - name: Añadir usuario 'roldyx' al grupo 'docker'
    action: user name=roldyx groups=docker 

  - name: Añadir usuario 'roldyx' al grupo 'libvirt'
    action: user name=roldyx groups='libvirt,kvm'

  - name: crear directorio /home/roldyx/.local/share/kxmlgui5/konsole
    file:
      path: /home/roldyx/.local/share/kxmlgui5/konsole
      state: directory

  - name: copiar archivo roldyx konsoleui.rc
    copy:
      src: files/konsoleui.rc
      dest: /home/roldyx/.local/share/kxmlgui5/konsole
      
  - name: crear directorio /home/cuzca/.local/share/kxmlgui5/konsole
    file:
      path: /home/cuzca/.local/share/kxmlgui5/konsole
      state: directory

  - name: copiar archivo cuzca konsoleui.rc
    copy:
      src: files/konsoleui.rc
      dest: /home/cuzca/.local/share/kxmlgui5/konsole

  - name: agregar modulo para el sensor de velocidad del Fan Cooler
    lineinfile:
      path: /etc/modules
      line: it87

  - name: ejecutar modules it87
    shell: modprobe it87

  - name: copiar archivo stern
    copy:
      src: files/stern
      dest: /home/roldyx/bin/stern

  - name: asegurar que en Ensure AuthorizedKeysFile is set to .ssh/authorized_keys
    lineinfile:   
      dest: /etc/systemd/system.conf
      regexp: DefaultTimeoutStopSec
      line: 'DefaultTimeoutStopSec=10s'

  - name: crear directorio /olddisk
    file:
      path: /olddisk
      state: directory
      
  - name: montar el viejo disco
    lineinfile:   
      dest: /etc/fstab
      line: 'UUID="7a558d52-ccfd-40f0-876b-a79eb439a101" /olddisk ext4 defaults 0 0'
      
